apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwcom-persistent-storage
  labels:
    app: nwcom
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-weather
