apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwcom
  labels:
    app: nwcom
spec:
  selector:
    matchLabels:
      app: nwcom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nwcom
    spec:
      containers:
      - image: jkozik/nw.com:v1.61
        name: nwcom
        ports:
        - containerPort: 80
          name: nwcom
        volumeMounts:
        - name: nwcom-persistent-storage
          mountPath: "/var/www/html/mount" 
      volumes:
      - name: nwcom-persistent-storage
        persistentVolumeClaim:
          claimName: nwcom-persistent-storage
